name: Docker Build CI

on:
  push:
    branches: [ main, feature-docker-compose ]
  pull_request:
    branches: [ main, feature-docker-compose ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker app image
        run: docker build -f Dockerfile.app -t test-app-image .

      - name: Build Docker logger image
        run: docker build -f Dockerfile.logger -t test-logger-image .
